name: ci-terraform

on:
  workflow_call:

permissions:
  contents: read

env:
  TF_IN_AUTOMATION: "true"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.9"

      - uses: terraform-linters/setup-tflint@v4

      - uses: astral-sh/setup-uv@v5

      - run: make terraform-fmt

      - run: make terraform-validate

      - run: make terraform-lint

      - run: make terraform-policy
